### ISSUE TITLE
obj.hasOwnProperty undefined in NodeJS 6.9.4

### ISSUE THREAD

**Issue by TaomusGrey** [osher/request-param#1]
Code which parses the request body and query no longer creates objects that have the Object prototype.

The fix is to use Object.prototype.hasOwnProperty.call(obj, name);

**Comment by osher** [comment]
I'd love to know what you're pointing at, and see what fix we can come with.
Can you be more specific or create a PR?

**Comment by osher** [comment]
ah. gotcha, thanks. 
will take care of it

**Comment by osher** [comment]
v1.0.1 published :)
